version: '2'
services:
 mysql:
   restart: always
   image: daocloud.io/library/mysql:5.7.11
   volumes:
   - /home/vcredit/dockerData/o2o-mysql/data:/var/lib/mysql
   - /home/vcredit/dockerData/o2o-mysql/backup:/var/lib/backup
   - /etc/localtime:/etc/localtime
   environment:
    MYSQL_ROOT_PASSWORD: vcredit_o2o(Mysql)
    --character-set-server: utf8mb4
   ports:
   - 3308:3306
   container_name: o2o-mysql
   mem_limit: 8g
