web:
  image: 'gitlab/gitlab-ce:8.9.0-rc6.ce.0'
  restart: always
  hostname: '10.154.40.80'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://10.154.40.80:9090'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '9090:9090'
    - '2224:22'
  volumes:
    - '/home/vcredit/dockerData/gitlab/data:/var/opt/gitlab'
  container_name: gitlab
